matrix:
  include:
    - language: php
      php:
        - '5.4'
        - '5.6'
        - '7.0'
        - '7.1'
        - '7.2'
        - '7.3'
  
      script:
        - chmod a+x classes/email_crawler.class.php
        - chmod a+x classes/config.class.php
